# Generated by Django 5.2.5 on 2025-08-26 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('room_name', models.CharField(max_length=64)),
            ],
        ),
    ]
